# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 405)
        Form.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background:#333;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:red;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"\n"
"QLineEdit \n"
"{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 110, 271, 188))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 40, 331, 321))
        self.label.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background:#333;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:red;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"\n"
"QLineEdit \n"
"{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 310, 141, 23))
        self.pushButton.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 310, 101, 23))
        self.pushButton_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-20, -40, 561, 531))
        self.label_2.setStyleSheet("image: url(:/uides/user.jpg)\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("W:/Оноприйчук Дмитрий Александрович/ИП-24-27б/09.12.24/images/form_background.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 40, 61, 61))
        self.label_3.setStyleSheet("image: url(:/uides/user.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Surname"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Username"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Login"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Зарегистрироваться"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))
import photo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
